import type { App, TFile } from 'obsidian';

import type { CodexProvider } from '../agent/CodexProvider';
import type { AgentEvent, MemoryMapResult } from '../types';
import type { SukgoTool } from './SukgoTools';

export interface RunSukgoRequest {
  app: App;
  agent: CodexProvider;
  vaultPath: string;
  outputFolder: string;
  tool: SukgoTool;
  topic: string;
  activeFile: TFile | null;
  activeNoteContent: string;
  selectedText?: string;
  pinnedNotes: Array<{ path: string; content: string }>;
  relatedNotes: Array<MemoryMapResult & { content?: string }>;
  onProgress?: (message: string) => void;
}

export interface RunSukgoResult {
  path: string;
  content: string;
}

export async function runSukgoAnalysis(request: RunSukgoRequest): Promise<RunSukgoResult> {
  const prompt = buildSukgoPrompt(request);
  let response = '';
  const errors: string[] = [];

  for await (const event of request.agent.query({
    prompt,
    cwd: request.vaultPath,
    activeNotePath: request.activeFile?.path,
    activeNoteContent: request.activeNoteContent,
    selectedText: request.selectedText,
    pinnedNotes: buildPinnedNotes(request),
  })) {
    handleAgentEvent(event, request.onProgress, (text) => {
      response += text;
    }, errors);
  }

  if (errors.length > 0 && !response.trim()) {
    throw new Error(errors.join('\n'));
  }

  const content = buildSukgoNote(request, response.trim() || errors.join('\n'));
  const path = await writeSukgoNote(request.app, request.outputFolder, request.tool, request.topic, content);
  return { path, content };
}

function handleAgentEvent(
  event: AgentEvent,
  onProgress: RunSukgoRequest['onProgress'],
  appendText: (text: string) => void,
  errors: string[],
): void {
  if (event.type === 'progress') onProgress?.(event.content);
  if (event.type === 'text') appendText(event.content);
  if (event.type === 'error') errors.push(event.content);
}

function buildPinnedNotes(request: RunSukgoRequest): Array<{ path: string; content: string }> {
  const related = request.relatedNotes
    .filter((note): note is MemoryMapResult & { content: string } => Boolean(note.content?.trim()))
    .map((note) => ({
      path: note.path,
      content: [
        `Related note score: ${note.score}`,
        `Reasons: ${note.reasons.join(', ') || 'n/a'}`,
        '',
        note.content,
      ].join('\n'),
    }));

  return [...request.pinnedNotes, ...related];
}

function buildSukgoPrompt(request: RunSukgoRequest): string {
  const source = request.activeFile
    ? `Active note: ${request.activeFile.path}`
    : 'No active note was available.';
  const topic = request.topic.trim()
    || request.selectedText?.trim()
    || request.activeFile?.basename
    || 'Untitled Obsidian topic';

  return [
    'You are running a Sukgo-style structured thinking workflow inside Obsidian.',
    'Use the active note, selected text, pinned notes, and related Memory Map notes as evidence.',
    'Clearly mark assumptions when the note context does not settle a point.',
    'Write in Korean unless the source material clearly calls for another language.',
    '',
    `Tool: ${request.tool.name}`,
    `Tool purpose: ${request.tool.shortDescription}`,
    `Source: ${source}`,
    `Topic: ${topic}`,
    '',
    'Framework instructions:',
    request.tool.prompt,
    '',
    'Output requirements:',
    '- Use Obsidian-friendly Markdown.',
    '- Start with a short conclusion.',
    '- Keep evidence from the note/context separate from inference.',
    '- End with concrete next actions or questions.',
  ].join('\n');
}

function buildSukgoNote(request: RunSukgoRequest, response: string): string {
  const now = new Date();
  const topic = request.topic.trim() || request.activeFile?.basename || 'Untitled';
  const sourceLink = request.activeFile ? `[[${request.activeFile.path.replace(/\.md$/i, '')}]]` : '';
  const relatedLinks = request.relatedNotes.map((note) => `[[${note.path.replace(/\.md$/i, '')}]]`);

  return [
    '---',
    `title: ${yamlString(`${request.tool.name} - ${topic}`)}`,
    `tool: ${yamlString(request.tool.id)}`,
    'mode: codexian-sukgo',
    `topic: ${yamlString(topic)}`,
    `source: ${yamlString(request.activeFile?.path || '')}`,
    `created: ${now.toISOString()}`,
    'tags:',
    '  - sukgo',
    `  - sukgo/${request.tool.id}`,
    '  - codexian',
    '---',
    '',
    `# ${request.tool.name} - ${topic}`,
    '',
    sourceLink ? `> [!info]+ Source\n> ${sourceLink}` : '',
    relatedLinks.length > 0 ? `> [!tip]- Related Memory Map notes\n${relatedLinks.map((link) => `> - ${link}`).join('\n')}` : '',
    '',
    response,
    '',
    '---',
    '',
    '> [!quote]- Sukgo metadata',
    `> Generated by Codexian Sukgo on ${now.toLocaleString()}`,
    `> Tool: ${request.tool.name}`,
  ].filter((line) => line !== '').join('\n');
}

async function writeSukgoNote(
  app: App,
  outputFolder: string,
  tool: SukgoTool,
  topic: string,
  content: string,
): Promise<string> {
  const folder = normalizeFolder(outputFolder || 'Sukgo');
  await ensureFolder(app, folder);
  const timestamp = formatTimestamp(new Date());
  const slug = slugify(topic || tool.name);
  let path = `${folder}/${timestamp}_${tool.id}_${slug}.md`;
  let counter = 2;
  while (await app.vault.adapter.exists(path)) {
    path = `${folder}/${timestamp}_${tool.id}_${slug}_${counter}.md`;
    counter += 1;
  }
  await app.vault.create(path, content);
  return path;
}

async function ensureFolder(app: App, folder: string): Promise<void> {
  const parts = folder.split('/').filter(Boolean);
  let current = '';
  for (const part of parts) {
    current = current ? `${current}/${part}` : part;
    if (!await app.vault.adapter.exists(current)) {
      await app.vault.createFolder(current);
    }
  }
}

function normalizeFolder(folder: string): string {
  return folder.replace(/\\/g, '/').replace(/^\/+|\/+$/g, '') || 'Sukgo';
}

function formatTimestamp(date: Date): string {
  const pad = (value: number) => String(value).padStart(2, '0');
  return [
    date.getFullYear(),
    pad(date.getMonth() + 1),
    pad(date.getDate()),
    '_',
    pad(date.getHours()),
    pad(date.getMinutes()),
  ].join('');
}

function slugify(value: string): string {
  const slug = value
    .trim()
    .replace(/[\\/:*?"<>|#^[\]]+/g, ' ')
    .replace(/\s+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 60);
  return slug || 'untitled';
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}
